#!/bin/bash

set -e

git clean -dfx
bash -e ./bootstrap
./configure --prefix=/usr/local
make

echo "[35mabout to make check (hit enter to continue)[m"
read X
make check | hi PASS green FAIL red

echo "[35mabout to make install (hit enter to continue)[m"
read X
make install prefix=`pwd`/../test.cbc
